//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cryptonit.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CryptonitEntities : DbContext
    {
        public CryptonitEntities()
            : base("name=CryptonitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<PublicKey> PublicKey { get; set; }
        public virtual DbSet<Recipient> Recipient { get; set; }
        public virtual DbSet<Signature> Signature { get; set; }
        public virtual DbSet<Transaction> Transaction { get; set; }
        public virtual DbSet<TransactionStatus> TransactionStatus { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserContact> UserContact { get; set; }
    }
}
